version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dorm-postgres
    environment:
      POSTGRES_DB: dorm-db
      POSTGRES_USER: admin@mail.com
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - dorm_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: dorm-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - dorm_pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  dorm_db_data:
  dorm_pgadmin_data:
